config/routes.rb
Teamate::Application.routes.draw do
  resources :users, :messages, :conversations, :sessions

  root :to => 'pages#home'
  get "pages/home"

  match 'pages/:id',
  :controller   => 'pages',
  :action       => 'show',
  :requirements => { :id => /[a-z]+/ }

  match 'login', :to => 'sessions#new'
  match 'logout', :to => 'sessions#destroy'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  has_many :messages
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  # GET /conversations
  # GET /conversations.xml
  def index
    @conversations = Conversation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @conversations }
    end
  end

  # GET /conversations/1
  # GET /conversations/1.xml
  def show
    @conversation = Conversation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @conversation }
    end
  end

  # GET /conversations/new
  # GET /conversations/new.xml
  def new
    @conversation = Conversation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @conversation }
    end
  end

  # GET /conversations/1/edit
  def edit
    @conversation = Conversation.find(params[:id])
  end

  # POST /conversations
  # POST /conversations.xml
  def create
    @conversation = Conversation.new(params[:conversation])

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to(@conversation, :notice => 'Conversation was successfully created.') }
        format.xml  { render :xml => @conversation, :status => :created, :location => @conversation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @conversation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /conversations/1
  # PUT /conversations/1.xml
  def update
    @conversation = Conversation.find(params[:id])

    respond_to do |format|
      if @conversation.update_attributes(params[:conversation])
        format.html { redirect_to(@conversation, :notice => 'Conversation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @conversation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.xml
  def destroy
    @conversation = Conversation.find(params[:id])
    @conversation.destroy

    respond_to do |format|
      format.html { redirect_to(conversations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= form_for(@conversation) do |f| %>
  <% if @conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% @conversation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing conversation</h1>

<%= render 'form' %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<h1>Listing conversations</h1>

<table class="zebra-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<% @conversations.each do |conversation| %>
  <tr>
    <td><%= link_to conversation.messages[0].title, conversation %></td>
    <td><%= link_to conversation.messages[0].user.name, :controller=>'users', :action=>'show', :id=>conversation.messages[0].user_id %></td>
    <td><%= link_to 'Edit', edit_conversation_path(conversation) %></td>
    <td><%= link_to 'Destroy', conversation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Conversation', new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New conversation</h1>

<%= render 'form' %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<div class="page-header">
    <h1><%= @conversation.messages[0].title %> <small> started by <%= @conversation.messages[0].user.name %></small></h1>
</div>
<ul class="breadcrumb">
    <li><%= link_to 'Home', '/' %> <span class="divider">&raquo;</span></li>
    <li><%= link_to 'Messages', conversations_path %> <span class="divider">&raquo;</span></li>
    <li class="active"><%= @conversation.messages[0].title %></li>
</ul>


<% i = 0; %>
<% @conversation.messages.each do |message| %>
<%
  i = i+1
  tmp = i%2
  even = ''
  if tmp == 0
    even = 'even'
  end
%>
<div class="well message <%= even %>">
    <div class="title">
        <a href="#"><img src="/images/stanko.png"/></a>
        <h3><%= message.title %></h3>
        <div class="date"><%= message.created_at %></div>
    </div>

    <div class="message-text">
        <p>
          <%= message.text %>
        </p>
    </div>
    <div class="info">
        Posted by <%= link_to message.user.name, message.user %> | <a href="#">Reply</a>
    </div>
</div>
<% end %>


<%= link_to 'Edit', edit_conversation_path(@conversation) %> |
<%= link_to 'Back', conversations_path %>