config/routes.rb
Teamate::Application.routes.draw do
  resources :users, :messages, :conversations, :sessions

  root :to => 'pages#home'
  get "pages/home"

  match 'pages/:id',
  :controller   => 'pages',
  :action       => 'show',
  :requirements => { :id => /[a-z]+/ }

  match 'login', :to => 'sessions#new'
  match 'logout', :to => 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<footer>
  <p>
    <%= link_to 'Home', '/' %> |
    <%= link_to 'Sitemap', '/' %> |
    <%= link_to 'About', '/' %> |
    <%= link_to 'Contact', '/' %>
  </p>

  <p>
    &copy;
    <%=  Time.new.year %>.
    RocketLaunch
  </p>
</footer>

app/views/layouts/_header.html.erb
<div class="topbar"> <div class="fill">
        <div class="container">
            <%= link_to image_tag("logo.png", :alt=>'Teamate')+'TeaMate', '/', {:class=>'brand'}%>
            <% if signed_in? %>
            <ul class="nav" id="menu">
                <li><a href="/" class="home-menu">Home</a></li>
                <li><a href="/conversations" class="messages-menu">Messages<!--span class="new-items">12</span--></a></li>
                <li><a href="/milestones" class="milestones-menu">Milestones</a></li>
                <li><a href="/todos" class="todos-menu">To-dos</a></li>
                <li><a href="/timetrackings" class="time-menu">Timetracking</a></li>
                <li><a href="/links" class="links-menu">Links</a></li>
            </ul>

            <div class="pull-right">
              Welcome <%= "#{current_user.name} #{current_user.last_name}" %>
              <a href="/logout" >Logout</a>
            </div>
            <% else%>
              <%= form_for(:session, :url => sessions_path, :html => {:class => "pull-right"}) do |f| %>
                <%= f.text_field :email, :class => "input-small", :placeholder => "Email" %>
                <%= f.password_field :password, :class => "input-small", :placeholder => "Password" %>
                <%= f.submit :class=>'btn primary', :value => "Login" %>
              <% end %>
            <% end %>
            </form>
        </div>
    </div>
</div>

app/views/layouts/_sidebar-menu.html.erb
<h3>Main menu</h3>
<ul>
    <li class="home-menu"><a href="index.php">Home</a>
        <span class="toggle-submenu"></span>
        <ul>
            <li><a href="#">Profile</a></li>
        </ul>
    </li>
    <li class="messages-menu"><a href="messages.php">Messages</a>
        <span class="toggle-submenu"></span>
        <ul>
            <li><a href="#">New message</a></li>

            <li><a href="#">All messages</a></li>
        </ul>
    </li>
    <li class="todos-menu"><a href="todos.php">To-dos</a>
        <span class="toggle-submenu"></span>
        <ul>
            <li><a href="#">New to-do</a></li>

            <li><a href="#">All to-dos</a></li>
        </ul>
    </li>
    <li class="milestones-menu"><a href="milestones.php">Milestones</a>
        <span class="toggle-submenu"></span>
        <ul>
            <li><a href="#">New milestone</a></li>

            <li><a href="#">All milestones</a></li>
        </ul>
    </li>
    <li class="links-menu"><a href="links.php">Timetrack</a><span class="toggle-submenu"></span></li>
    <li class="links-menu"><a href="links.php">Links</a>
        <span class="toggle-submenu"></span>
        <ul>
            <li><a href="#">New link</a></li>

            <li><a href="#">Newest</a></li>
            <li><a href="#">Top rated</a></li>
        </ul>
    </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>TeaMate</title>
    <meta name="description" content="Project managment app aimed to small development teams.">
    <meta name="author" content="RocketLaunch">

    <!-- Sttyles -->
    <%= stylesheet_link_tag "bootstrap.css", "style.css"%>

    <!-- Scripts -->
    <%= javascript_include_tag "jquery-1.6.4.min.js", "rails.js"%>
    <%= javascript_include_tag "jquery.tablesorter.min.js", "easing.js", "jquery.bbcodeeditor-1.0.js" %>
    <%= javascript_include_tag "bs/bootstrap-tabs.js" %>
    <%= javascript_include_tag "scripts.js" %>


    <!-- E6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <%= javascript_include_tag "ie.js"%>
    <![endif]-->

    <!-- Fv and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
</head>
<body>

    <%= render 'layouts/header' %>

    <div class="container">
        <div class="content">
            <%= yield %>
        </div>

        <%= render 'layouts/footer' %>

    </div> <!-- /container -->

  </body>
</html>